# Generated by Django 5.0.1 on 2024-02-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Event Name")),
                ("date", models.DateTimeField(verbose_name="Event Date")),
                ("venue", models.CharField(max_length=120)),
                ("manager", models.CharField(max_length=60)),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
