# Generated by Django 5.0.1 on 2024-02-02 18:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="date",
            new_name="event_date",
        ),
    ]
